version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name MyWebApp --s3-location s3://my-web-app-artifacts-unique-name/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src